import { Props as AliasProps } from "@components/blocks/alias";
import { Props as AssetProps } from "@components/blocks/asset";
import { Props as AudioProps } from "@components/blocks/audio";
import { Props as BookmarkProps } from "@components/blocks/bookmark";
import { Props as BulletedListProps } from "@components/blocks/bulleted-list";
import { Props as CalloutProps } from "@components/blocks/callout";
import { Props as ColumnProps } from "@components/blocks/column";
import { Props as ColumnListProps } from "@components/blocks/column-list";
import { Props as CodeProps } from "@components/blocks/code";
import { Props as CollectionViewPageProps } from "@components/blocks/page";
import { Props as CollectionViewProps } from "@components/blocks/collection-view";
import { Props as DividerProps } from "@components/blocks/divider";
import { Props as EquationProps } from "@components/blocks/equation";
import { Props as FileProps } from "@components/blocks/file";
import { Props as HeaderProps } from "@components/blocks/header";
import { Props as ImageProps } from "@components/blocks/image";
import { Props as NumberedListProps } from "@components/blocks/numbered-list";
import { Props as PageProps } from "@components/blocks/page";
import { Props as PdfProps } from "@components/blocks/pdf";
import { Props as QuoteProps } from "@components/blocks/quote";
import { Props as TransclusionContainerProps } from "@components/blocks/transclusion-container";
import { Props as TransclusionReferenceProps } from "@components/blocks/transclusion-reference";
import { Props as TableOfContentsProps } from "@components/blocks/table-of-contents";
import { Props as TextProps } from "@components/blocks/text";
import { Props as TodoProps } from "@components/blocks/to-do";
import { Props as ToggleProps } from "@components/blocks/toggle";

export type Presenter<T> = (props: T) => React.ReactElement;

export interface Any {
  alias: Presenter<AliasProps>;
  audio: Presenter<AudioProps>;
  bookmark: Presenter<BookmarkProps>;
  bulletedList: Presenter<BulletedListProps>;
  callout: Presenter<CalloutProps>;
  column: Presenter<ColumnProps>;
  columnList: Presenter<ColumnListProps>;
  code: Presenter<CodeProps>;
  codepen: Presenter<AssetProps>;
  collectionViewPage: Presenter<CollectionViewPageProps>;
  collectionView: Presenter<CollectionViewProps>;
  divider: Presenter<DividerProps>;
  drive: Presenter<AssetProps>;
  excalidraw: Presenter<AssetProps>;
  embed: Presenter<AssetProps>;
  equation: Presenter<EquationProps>;
  file: Presenter<FileProps>;
  figma: Presenter<AssetProps>;
  gist: Presenter<AssetProps>;
  header: Presenter<HeaderProps>;
  image: Presenter<ImageProps>;
  maps: Presenter<AssetProps>;
  numberedList: Presenter<NumberedListProps>;
  page: Presenter<PageProps>;
  pdf: Presenter<PdfProps>;
  quote: Presenter<QuoteProps>;
  subHeader: Presenter<HeaderProps>;
  subSubHeader: Presenter<HeaderProps>;
  tableOfContents: Presenter<TableOfContentsProps>;
  text: Presenter<TextProps>;
  transclusionContainer: Presenter<TransclusionContainerProps>;
  transclusionReference: Presenter<TransclusionReferenceProps>;
  todo: Presenter<TodoProps>;
  toggle: Presenter<ToggleProps>;
  tweet: Presenter<AssetProps>;
  video: Presenter<AssetProps>;
}
